/*
The following values represent the the collumn sizes in the ui
the main ui has a margin of 4, and any ui control starts at 13
*/

width = 360
superwidth = width+32
contentWidth = width-26
widthA = contentWidth/6
widthB = widthA*2
widthC = widthA*3
widthD = widthA*4
widthE = widthA*5
widthF = widthA*6

colA = 13
colB = widthA+13
colC = widthB+13
colD = widthC+13
colE = widthD+13
colF = widthE+13

spCorr = widthA-13

mid = ((width/2) + 12)
height = 788